name: na_posters_app
description: NA Posters Flutter app
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  http: ^0.13.3
  image_picker: ^0.8.4+2
  path: ^1.8.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
