name: na_posters_app
description: NA Posters Flutter app
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  sqflite: any
  path_provider: any
  http: any
  path: any
  shared_preferences: any
  archive: any
  permission_handler: any

  # Map & Location
  google_maps_flutter: ^2.6.1
  geolocator: any
  flutter_polyline_points: any # Para desenhar rotas

  # UI & Features
  image_picker: any
  signature: any
  share_plus: any
  intl: any
  google_fonts: ^6.3.1

  # Firebase
  firebase_core: any
  firebase_app_check: any
  firebase_app_installations: any
  cloud_firestore: any
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  flutter_map: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  firebase_core_platform_interface: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
