name: na_posters_app
description: NA Posters Flutter app
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.1.5
  flutter_map: ^8.0.0
  latlong2: ^0.9.0
  http: ^1.0.0
  image_picker: ^1.2.0
  path: ^1.9.1
  geolocator: ^14.0.2
  flutter_map_location_marker: ^10.1.0
  signature: ^6.3.0
  archive: ^4.0.7
  share_plus: ^12.0.0
  permission_handler: ^12.0.1
  firebase_core: ^4.1.0
  firebase_app_check: ^0.4.0+1
  firebase_app_installations: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
