name: na_posters_app
description: NA Posters Flutter app
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  http: ^1.2.1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  archive: ^3.5.1
  permission_handler: ^11.3.1

  # Map & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  flutter_map_location_marker: ^8.0.3

  # UI & Features
  image_picker: ^1.1.2
  signature: ^5.1.0
  share_plus: ^9.0.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_app_check: ^0.2.2
  firebase_app_installations: ^0.2.5
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
