// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2g3nFEphn_oDzdatpOm1gC0n2Kqkw2dI',
    appId: '1:478846934430:web:3d472d707c44ac27874a8f',
    messagingSenderId: '478846934430',
    projectId: 'postersna-99a68',
    authDomain: 'postersna-99a68.firebaseapp.com',
    storageBucket: 'postersna-99a68.firebasestorage.app',
    measurementId: 'G-YSMG1ZKNXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkj-PWMSnf0UvI5LXSt5eRY6KugRqMSzs',
    appId: '1:478846934430:android:85caca32a3e57071874a8f',
    messagingSenderId: '478846934430',
    projectId: 'postersna-99a68',
    storageBucket: 'postersna-99a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzniONZ0rSES73ApX4wFWRSh5mTtf354U',
    appId: '1:478846934430:ios:d652565d0ef90d0b874a8f',
    messagingSenderId: '478846934430',
    projectId: 'postersna-99a68',
    storageBucket: 'postersna-99a68.firebasestorage.app',
    iosBundleId: 'com.example.naPostersApp',
  );
}
